services:
  cantina.web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cantina.api
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - OTLP_ENDPOINT_URL=http://otel-collector:4317
    depends_on:
      - cantina.database
      - cantina.cache
  cantina.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cantina.database
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Developer

  cantina.cache:
    image: redis/redis-stack:latest
    restart: always
    container_name: cantina.cache
    ports:
      - "6379:6379"
  cantina.syncservice:
    image: tjabane/cantina.syncservice
    container_name: cantina.syncservice
    depends_on:
      - cantina.database
      - cantina.cache
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  jaeger:
    image: jaegertracing/all-in-one:1.41
    container_name: jaeger
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "4317:4317" # gRPC port for receiving traces
      - "8888:8888" # HTTP port for receiving traces
    volumes:
      - ./monitoring/otel-collector-config.yaml:/otel-local-config.yaml
    command:
      - '--config=/otel-local-config.yaml'
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus