services:
  cantina.web:
    image: ${DOCKER_REGISTRY-}cantinaweb
    container_name: cantina.web
    build:
      context: .
      dockerfile: Cantina.Web/Dockerfile
  cantina.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cantina.database
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
      - MSSQL_PID=Developer
    volumes:
      - sqlserverdata:/var/opt/mssql 

  cantina.cache:
    image: redis/redis-stack:latest
    restart: always
    container_name: cantina.cache
    ports:
      - "6379:6379"
volumes:
  sqlserverdata:
    driver: local